server.port=8080

spring.datasource.url=jdbc:h2:mem:chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL for debugging (optional)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# File Upload Configuration (10GB)
spring.servlet.multipart.max-file-size=10240MB
spring.servlet.multipart.max-request-size=10240MB
